spring:
  application:
    name: axiom
  datasource:
    url: jdbc:postgresql://localhost:5432/axiom
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20

server:
  port: 8080

axiom:
  jwt:
    secret: ${JWT_SECRET:pWBQsq3S2SwhGCaRzRjVrUk4RJBbvxcSd7r5TdF0ChYBJrxojc4Ehyxl6QdonJ7y}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  admin:
    email: ${ADMIN_EMAIL:admin@axiom.local}
    password: ${ADMIN_PASSWORD:iloveaxiom}
